/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseMailbox_AccountBase : EntityMailbox
	{
		public EntityBaseMailbox_AccountBase() : base()
		{
			type = MAILBOX_TYPE.MAILBOX_TYPE_BASE;
		}

		public void ReCreateAccountRequest(Int16 arg1, string arg2)
		{
			Bundle pBundle = newMail("ReCreateAccountRequest");
			if(pBundle == null)
				return;

			bundle.writeInt16(arg1);
			bundle.writeUnicode(arg2);
			postMail(null);
		}

	}

	public class EntityCellMailbox_AccountBase : EntityMailbox
	{
		public EntityCellMailbox_AccountBase() : base()
		{
			type = MAILBOX_TYPE.MAILBOX_TYPE_CELL;
		}

	}
	}
