/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseEntityCall_AccountBase : EntityCall
	{

		public EntityBaseEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void AttackChess(Int32 arg1, Int32 arg2, Int32 arg3, Int32 arg4)
		{
			Bundle pBundle = newCall("AttackChess", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt32(arg2);
			bundle.writeInt32(arg3);
			bundle.writeInt32(arg4);
			sendCall(null);
		}

		public void ChessMove(Int32 arg1, Int32 arg2, Int32 arg3)
		{
			Bundle pBundle = newCall("ChessMove", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			bundle.writeInt32(arg2);
			bundle.writeInt32(arg3);
			sendCall(null);
		}

		public void ClientReady()
		{
			Bundle pBundle = newCall("ClientReady", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void EntryFBScene()
		{
			Bundle pBundle = newCall("EntryFBScene", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void ReCreateAccountRequest(Int16 arg1, string arg2)
		{
			Bundle pBundle = newCall("ReCreateAccountRequest", 0);
			if(pBundle == null)
				return;

			bundle.writeInt16(arg1);
			bundle.writeUnicode(arg2);
			sendCall(null);
		}

		public void TestChessEntity(UInt64 arg1)
		{
			Bundle pBundle = newCall("TestChessEntity", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountBase : EntityCall
	{

		public EntityCellEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

	}
	}
